### ISSUE TITLE
Script fails on OSMC

### ISSUE THREAD

**Issue by sa7mon** [EmilGus/install_raspi-config#2]
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="September 2015"
VERSION_ID="2015.09-2"

The script works fine checking for dependencies until it tries to install the debian package and fails with this message:
dpkg: error processing archive raspi-config_20121028_all.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 raspi-config_20121028_all.deb

However, I was able to manually install the package after wget'ing it and running "dpkg -i package.deb"

**Comment by ppigmans** [comment]
hey if you are still having that issue its because he messed up, if you look at the script it self it says he downloads a 2015 version, and then tries to install the 2012 one, i got it fixed on my repo, check it out

**Comment by EmilGus** [comment]
Fixed the issue.
