### ISSUE TITLE
Raspberry Pi 4 with Ubuntu 20.04

### ISSUE THREAD

**Issue by safariace** [EmilGus/install_raspi-config#9]
Given the RPi4 has a whole new boot loader for launching from SD card, I was able to use your script to install RASPI-CONFIG on Ubuntu 20.04 but when I launch it I get:

The boot partition is not mounted - cannot configure.

Any suggestions on how I might get that to work?

**Comment by EmilGus** [comment]
> Check if your boot folder is empty using cd /boot/ in a terminal session. If so, you should be able to mount it to the SD card using a simple command.
> sudo mount /dev/mmcblk0p1 /boot
https://raspberrypi.stackexchange.com/a/50646

Try that, let me know if it works. If the boot folder isn't empty, see if you can find the config.txt.

**Comment by safariace** [comment]
I found config.txt in /boot/firmware

With the following info inside the file:

# Please DO NOT modify this file; if you need to modify the boot config, the 'usercfg.txt' is the place to include user changes.

Would RASPI-CONFIG know to change the files in this new setup properly?

I'm trying to disable the console on the RPi 4 on Ubuntu 20.04.  Right now this is what I get:

dmesg | grep tty
[    0.001060] printk: console [tty0] enabled
[    1.917157] fe201000.serial: ttyAMA0 at MMIO 0xfe201000 (irq = 29, base_baud = 0) is a PL011 rev2
[    1.922470] fe215040.serial: ttyS0 at MMIO 0x0 (irq = 31, base_baud = 62500000) is a 16550

Which means the console is enabled and should explain why I'm unable to get the serial working.  I have loopback on Pin 8,10, have run minicom on ttyS0 and get nothing. 

Goal is to get serial working, which means I need to disable the console.  Which took RASPI-CONFIG on Raspbian.

**Comment by EmilGus** [comment]
Let me see if I understand.
You are able to install the raspi-config with my script, but when running raspi-config it returns the error "The boot partition is not mounted - cannot configure". Is that right?

I have updated the script with references to the latest raspi-config packages. Maybe try the new one.

**Comment by safariace** [comment]
This did install successfully.  So that may be the extent of what you can help me with.  When I run RASPI-CONFIG the UI comes up but any attempt to use it reveals it's looking in the wrong directory for where a Raspberry Pi 4 keeps it's files.

ubuntu@ubuntu:~/Code/catkin_ws/src$ **sudo raspi-config**
grep: /boot/cmdline.txt: No such file or directory
sed: can't read /boot/cmdline.txt: No such file or directory
sed: can't read /boot/cmdline.txt: No such file or directory

the /boot/ directory has the following:

**ls /boot/**
System.map-5.4.0-1012-raspi      firmware
System.map-5.4.0-1013-raspi      initrd.img
config-5.4.0-1012-raspi               initrd.img-5.4.0-1012-raspi
config-5.4.0-1013-raspi               initrd.img-5.4.0-1013-raspi
config.txt                                      initrd.img.old
dtb                                               vmlinuz
dtb-5.4.0-1012-raspi                   vmlinuz-5.4.0-1012-raspi
dtb-5.4.0-1013-raspi                   vmlinuz-5.4.0-1013-raspi
dtbs                                             vmlinuz.old

which helps to locate the file it's looking for in /boot/firmware

Do you know of any override settings on RASPI to setup it's directory map correctly?

**Comment by SpereShelde** [comment]
Exactly same here...
